### ISSUE TITLE
Change name of OfferLogic and LiquidityProvider in SDK to match Solidity

### ISSUE THREAD

**Issue by peterMangrove** [mangrovedao/mangrove.js#1140]
**Is your feature request related to a problem? Please describe.**
The naming of OfferLogic and LiquidityProvider in the SDK and Solidity does not seem to match very well. Since an `ILiquidityProvider` from solidity is the same as an `OfferLogic` in the SDK. This is going to be the source of some confusion. 

![image](https://user-images.githubusercontent.com/105609241/217516414-3bccbec2-e268-4770-a607-81eac3252d43.png)

**Describe the solution you'd like**
Rename the classes in the SDK to match the solidity code. If we have any helper classes like `LiquidityProvider` in the SDK that is not a Solidity contract/interface, then come up with a new fitting name.

**Describe alternatives you've considered**

**Additional context**

**Comment by lnist** [comment]
The situation around LiquidityProvider in the SDK is not good at the moment, however, the issue here is not correct anymore. OfferLogic in the SDK and solidity does correlate.
