### ISSUE TITLE
`Mangrove` API should provide wrapped calls over all ethers call to Mangrove

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove.js#143]
To make more elegant and uniform code, Mangrove class should systematically provide wrapped calls to external functions of mangrove.

**Comment by peterMangrove** [comment]
@jkrivine Do you think this issue is still relevant? And if so, could you add a more detailed description of the issue?

**Comment by lnist** [comment]
Too vague. When missing, needed functions appear, we'll add them.
