### ISSUE TITLE
Parrot: Read `mangrove.js` addresses from JSON files in npm package

### ISSUE THREAD

**Issue by espendk** [mangrovedao/mangrove.js#242]
**Is your feature request related to a problem? Please describe.**
Parrot (`mgv parrot`) currently uses the addresses of the local `mangrove.js` install instead of the latest package on npm and its reporting is therefore imprecise.

**Describe the solution you'd like**
One of the FIXMEs in [parrotCmd.ts](https://github.com/mangrovedao/mangrove/blob/master/packages/mangrove.js/src/cli/commands/parrotCmd.ts) is followed by a commented out line which shows how to obtain the URL for the latest package on npm: https://github.com/mangrovedao/mangrove-ts/blob/master/packages/mangrove.js/src/cli/commands/parrotCmd.ts#L452

This package should be fetched and unpacked and then the addresses can be read from `dist/nodejs/constants/addresses.json`.

All FIXMEs in parrotCmd.ts that call out this issue + the generated warnings and notes on this should be addressed and removed.

**Describe alternatives you've considered**
None

**Additional context**
The solution for this issue is provided by PR #241 which partially addresses #134.

**Comment by lnist** [comment]
The parrot is dead
