### ISSUE TITLE
Parrot's fetching of deployment info is broken

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove.js#778]
Parrot should be updated [here](https://github.com/mangrovedao/mangrove-ts/blob/master/packages/mangrove.js/src/cli/commands/parrotCmd.ts#L426) to reflect the new deployment method.

**Comment by peterMangrove** [comment]
Parrot is no longer used. The goal is that an alert system like Grafana will be able to handle all the use cases Parrot had before. This issue is therefor low priority.

**Comment by espendk** [comment]
Parrot has been killed
