### ISSUE TITLE
Approving Mangrove on the taker side should approve both Mangrove and MangroveOrder

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove.js#842]
As a pure maker it is complicated to approve MangroveOrder (as one needs to approve its router). The `approveMangrove` function should approve both Mangrove and Mangrove order

**Comment by jkrivine** [comment]
+1 on this (or have an explicit `approveMgvOrder` function

**Comment by peterMangrove** [comment]
`ApproveMangrove` in the `MgvToken` class should also approve MangroveOrder

**Comment by lnist** [comment]
Closing since approval flows in UI have been reworked an new contracts will change approval flow.
