### ISSUE TITLE
Update README.md for mangrove.js along with api-overview.md from docs

### ISSUE THREAD

**Issue by lnist** [mangrovedao/mangrove.js#907]
The examples in the README are to some extend covered by docs.mangrove.exchange, and the api-overview.md there is also somewhat covered. Additionally, I believe some of the examples are out of date. They could benefit from being rewritten similar to the other howtos/tutorials.

**Comment by peterMangrove** [comment]
@dontrolle is this the same as #478 ?

**Comment by dontrolle** [comment]
No, this issue refers to this one, which still needs to be improved (cf the other issue) https://github.com/mangrovedao/mangrove-ts/blob/master/packages/mangrove.js/README.md

**Comment by lnist** [comment]
README.md has been updated, and docs is covered by another workstream, so closing.
